---
title: "Examples shown in the R Journal manuscript"
output: github_document
date: "2022-11-10"
params:
  save_image: FALSE
  cache: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = params$cache, dpi = 150, out.width = "100%")
```

```{r eval=TRUE}
set.seed(1234)
library(openalexR)
library(tidyverse)
library(knitr)
library(gghighlight)
theme_set(
  theme_classic() +
    theme(
      plot.background = element_rect(fill = "transparent", colour = NA),
      panel.background = element_rect(fill = "transparent", colour = NA),
      strip.background = element_rect(fill = NA, color = "grey20")
    )
)
```

## Bibliometrics concept
```{r load-data, include = FALSE, eval=FALSE}
# load("data/oarj.rdata")
```

```{r}
concept <- oa_fetch(
  entity = "concepts",
  identifier = "C178315738" # OAID for "bibliometrics"
)

cat(concept$description, "is a level", concept$level, "concept")

related_concepts <- concept$related_concepts[[1]] |>
  mutate(relation = case_when(
    level < 2 ~ "ancestor",
    level == 2 ~ "equal level",
    TRUE ~ "descendant"
  )) |>
  arrange(level) |>
  relocate(relation) |>
  select(-wikidata)

related_concepts
equal_ids <- related_concepts |>
  filter(relation == "equal level") |>
  pull(id)
```

## Trends of biliometrics-related concepts

```{r}
concept_df <- oa_fetch(
  entity = "concepts",
  identifier = c(concept$id, equal_ids)
)

biblio_concepts <- concept_df |>
  select(display_name, counts_by_year) |>
  tidyr::unnest(counts_by_year) |>
  filter(year < 2022) |>
  mutate(year = as.Date(paste0("1jan", year), format = "%d%b%Y")) |>
  ggplot() +
  aes(x = year, y = works_count, color = display_name) +
  scale_color_viridis_d(option = "B", end = 0.8) +
  facet_wrap(~display_name) +
  geom_line(linewidth = 0.7) +
  labs(x = NULL, y = "Works count") +
  scale_y_log10() +
  scale_x_date(labels = scales::date_format("'%y")) +
  guides(color = "none") +
  gghighlight(use_direct_label = FALSE)
biblio_concepts
```


```{r save-concepts, eval=params$save_image}
ggsave("images/biblio-concepts.png", biblio_concepts,
  dpi = 450, width = 7, height = 5
)
```

## Bibliometrics papers

```{r biblio-works, eval=FALSE}
oa_fetch(
  entity = "works",
  title.search = "bibliometrics|science mapping",
  count_only = TRUE,
  verbose = TRUE
)

biblio_works <- oa_fetch(
  entity = "works",
  title.search = "bibliometrics|science mapping",
  count_only = FALSE,
  verbose = TRUE
)
```


```{r biblio-works-load, include=FALSE}
# saveRDS(biblio_works, "data/biblio-works.rds")
biblio_works <- readRDS("data/biblio-works.rds")
```


```{r biblio-journal}
biblio_works |>
  count(so) |>
  drop_na(so) |>
  slice_max(n, n = 5) |>
  pull(so)

biblio_journal <- biblio_works |>
  add_count(so, name = "n_so") |>
  count(so, publication_year, n_so, sort = TRUE) |>
  drop_na(so) |>
  mutate(so_rank = dense_rank(desc(n_so))) |>
  filter(so_rank < 6, publication_year < 2022) |>
  mutate(
    so = gsub("International Journal of|Journal of the|Journal of", "I.J.", so) |>
      as_factor() |>
      fct_reorder(so_rank)
  ) |>
  complete(so, publication_year, fill = list(n = 0)) |>
  mutate(
    label = if_else(publication_year == max(publication_year),
      as.character(so), NA_character_
    )
  ) |>
  ggplot(aes(x = publication_year, y = n, fill = so)) +
  geom_area(alpha = 0.7, color = "white") +
  geom_text(aes(label = label, color = so, x = publication_year + 1),
    position = position_stack(vjust = 0.5),
    hjust = 0, na.rm = TRUE
  ) +
  scale_y_continuous(expand = expansion(add = c(0, 0))) +
  scale_x_continuous(
    expand = expansion(add = c(0, 22.5)),
    breaks = c(1980, 2000, 2020)
  ) +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "Number of works", x = NULL) +
  theme_minimal() +
  theme(panel.grid.minor.y = element_blank()) +
  guides(fill = "none", color = "none")

biblio_journal
```


```{r save-journal, eval=params$save_image}
ggsave("images/biblio-journals.png", biblio_journal,
  dpi = 450, height = 5, width = 10
)
```


```{r biblio-authors}
biblio_authors_raw <- do.call(rbind.data.frame, biblio_works$author)
biblio_insts <- biblio_authors_raw |>
  count(institution_display_name) |>
  rename("name" = institution_display_name) |>
  drop_na(name) |>
  slice_max(n, n = 10) |>
  mutate(type = "Institution")

biblio_authors <- biblio_authors_raw |>
  count(au_display_name) |>
  rename("name" = au_display_name) |>
  drop_na(name) |>
  slice_max(n, n = 10) |>
  mutate(type = "Author")

biblio_aut_insts <- biblio_authors |>
  bind_rows(biblio_insts) |>
  group_by(type) |>
  mutate(name = forcats::fct_reorder(name, n)) |>
  ggplot() +
  aes(x = n, y = name) +
  geom_segment(aes(yend = name, x = 0, xend = n)) +
  geom_point(aes(color = type), size = 3) +
  facet_wrap(~type, scales = "free") +
  scale_color_manual(values = c("#d46780", "#a3ad62"), guide = "none") +
  labs(x = "Number of articles", y = NULL) +
  theme(panel.spacing = unit(3, "lines"))

biblio_aut_insts

# authors <- bind_rows(small_biblio_works$author) |>
#   filter(author_position %in% c("first", "last"))

# authors |>
#   drop_na(institution_display_name) |>
#   count(institution_display_name, sort = TRUE)
```

```{r save-author, eval=params$save_image}
ggsave("images/biblio-authors-institutions.png", biblio_aut_insts,
  dpi = 450, height = 3.5, width = 8
)
```


## Two most cited articles and their citations and references

```{r snowball}
library(ggraph)
library(tidygraph)

seminal_works <- slice_max(biblio_works, cited_by_count, n = 8)
seminal_works$display_name

work_labels <- seminal_works[1:2, ] |>
  show_works() |>
  mutate(label = paste(word(first_author, 3, -1), "et al.")) |>
  select(id, label) |>
  deframe()

work_labels

snowball_docs <- oa_snowball(
  identifier = seminal_works$id[1:2],
  verbose = TRUE
)

snow_graph <- as_tbl_graph(snowball_docs)

snowball_small <- snowball_docs |>
  as_tbl_graph() |>
  slice(1:500)

g_citation <- ggraph(graph = snow_graph, layout = "stress") +
  geom_edge_link(alpha = 0.02) +
  geom_node_point(
    data = ~ filter(.x, !oa_input),
    mapping = aes(size = cited_by_count),
    fill = "#a3ad62",
    shape = 21, color = "white"
  ) +
  geom_node_point(
    data = ~ filter(.x, oa_input),
    mapping = aes(size = cited_by_count),
    fill = "#d46780",
    shape = 21, color = "white"
  ) +
  theme_graph() +
  theme(legend.position = "bottom") +
  theme(
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    strip.background = element_rect(fill = NA, color = "grey20")
  ) +
  guides(fill = "none", size = "none") +
  geom_node_label(aes(filter = oa_input, label = work_labels[id]), nudge_y = 0.2, size = 3)
g_citation
```


```{r}
library(ggraph)
seminal_works <- slice_max(biblio_works, cited_by_count, n = 10)
info_seminal_works <- seminal_works %>% 
  select(publication_year, display_name, so, cited_by_count)

info_seminal_works <- as.data.frame(info_seminal_works)
info_seminal_works

sb_docs <- oa_snowball(
  identifier = seminal_works$id[1:2],
  citing_filter = list(from_publication_date = "2022-01-01"),
  verbose = TRUE
)
sg_1 <- tidygraph::as_tbl_graph(sb_docs)

AU <- sb_docs$nodes %>% 
  select(author) |> 
  unlist(recursive = FALSE) |> 
  lapply(function(l) {paste(l$au_display_name, collapse = "; ")}) |> 
  unlist()

g_citation <- ggraph(graph = sg_1, layout = "stress") +
  aes(size = cited_by_count) +
  geom_edge_link(color = "grey60", alpha = 0.30, show.legend = FALSE) + 
  scale_edge_width(range = c(0.1, 1.5), guide = "none") + 
  scale_size(range = c(1, 3), guide = "none") + 
  geom_node_point(aes(filter = !oa_input), fill = "#a3ad62", shape = 21, color = "white") +
  geom_node_point(aes(filter = oa_input), fill = "#d46780", shape = 21, color = "white") +
  theme_graph() + 
  guides(fill = "none", size = "none") + 
  geom_node_label(aes(filter = oa_input, label = AU), nudge_y = 0.2, size = 3)
g_citation

# N-grams
options("oa_ngrams.message.curlv5" = TRUE)
ngrams_data <- oa_ngrams(biblio_works$id |> sample(1000), verbose = TRUE)
top_10 <- do.call(rbind.data.frame, ngrams_data$ngrams) |> 
  filter(ngram_tokens == 2) |> 
  arrange(desc(ngram_count)) |> 
  filter(nchar(ngram) > 10) |> 
  slice_max(ngram_count, n = 10, with_ties = FALSE)
top_10
library(treemapify)
treemap <- ggplot(top_10, aes(area = ngram_count, fill = ngram)) +
  scale_fill_viridis_d() +
  geom_treemap()
treemap

library(treemap)

treemap(dtf = top_10,
        index = c("ngram_count", "ngram"),
        vSize = "ngram_count",
        vColor = "ngram"
        )

```

```{r save-snowball, eval=params$save_image}
ggsave("images/citation-graph.png", g_citation,
  height = 5, width = 8
)
# save.image("data/oarj.rdata")
```

```{r}
session_info()
```
